// prettier-ignore-file
/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
 *
 * This file is automatically generated by Rhine Lint.
 * Any manual changes will be overwritten on the next run.
 *
 * To customize ESLint rules, please edit your rhine-lint.config file.
 * @see https://github.com/RhineAI/rhine-lint
 */

/* eslint-disable */

import { createJiti } from "file:///C:/Projects/rhine-lint/node_modules/jiti/lib/jiti.cjs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import createConfig from "file:///C:/Projects/rhine-lint/dist/assets/eslint.config.js";
import { defu } from "file:///C:/Projects/rhine-lint/node_modules/defu/lib/defu.cjs";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const jiti = createJiti(__filename);


const loaded = await jiti.import("C:/Projects/rhine-lint/playground/node_modules/.cache/rhine-lint/rhine-lint.user-config.mjs", { default: true });
const userOne = loaded.default || loaded;


const userEslint = userOne.eslint || {};
const level = "normal";
const typescript = true;

// Project-based type checking: CLI flag (true) takes precedence over config file
const projectTypeCheck = true || userOne.projectTypeCheck || false;

// TSConfig path: CLI flag takes precedence over config file
const tsconfigPath = null || userOne.tsconfig || null;

// 根据 level 和 typescript 计算启用的规则
let overrides = {
  ENABLE_TYPE_CHECKED: typescript,
  ENABLE_PROJECT_BASE_TYPE_CHECKED: typescript && projectTypeCheck,
  ENABLE_FRONTEND: level === "react" || level === "next",
  ENABLE_NEXT: level === "next",
};
if (tsconfigPath) {
  overrides.TSCONFIG_PATH = tsconfigPath;
}

const defaultEslint = createConfig(overrides);
let finalConfig;
const prefixConfig = [];


prefixConfig.push({ ignores: ["**/node_modules/**","**/dist/**","**/.next/**","**/.git/**","**/.output/**","**/.nuxt/**","**/coverage/**","**/.cache/**","**/out/**","**/*.tgz","**/*.lcov","**/logs/**","**/_.log","**/report.[0-9]_.[0-9]_.[0-9]_.[0-9]_.json","**/.env/**","**/.env.development.local","**/.env.test.local","**/.env.production.local","**/.env.local","**/.eslintcache/**","**/*.tsbuildinfo","**/.idea/**","**/.DS_Store/**","**/package-lock.json","**/yarn.lock","**/pnpm-lock.yaml","**/bun.lock"] });


if (false || userEslint.overlay) {
    // overlay=true: 用户配置完全覆盖内置配置
    const userConf = userEslint.config || [];
    if (Array.isArray(userConf)) {
        finalConfig = [...prefixConfig, ...userConf];
    } else {
        finalConfig = [...prefixConfig, userConf];
    }
} else {
    // overlay=false: 内置配置 + 用户配置追加
    const userConf = userEslint.config || [];
    const defaultConf = Array.isArray(defaultEslint) ? defaultEslint : [defaultEslint];
    finalConfig = [...prefixConfig, ...defaultConf, ...userConf];
}

export default finalConfig;
