// prettier-ignore-file
/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
 *
 * This file is automatically generated by Rhine Lint.
 * Any manual changes will be overwritten on the next run.
 *
 * To customize Prettier options, please edit your rhine-lint.config file.
 * @see https://github.com/RhineAI/rhine-lint
 */

/* eslint-disable */

import { createJiti } from "file:///C:/Projects/rhine-lint/node_modules/jiti/lib/jiti.cjs";
import defaultOne from "file:///C:/Projects/rhine-lint/dist/assets/prettier.config.js";
import { defu } from "file:///C:/Projects/rhine-lint/node_modules/defu/lib/defu.cjs";

const jiti = createJiti(import.meta.url);


const loaded = await jiti.import("file:///C:/Projects/rhine-lint/playground/rhine-lint.config.ts", { default: true });
const userOne = loaded.default || loaded;


const userPrettier = userOne.prettier || {};
const defaultPrettier = defaultOne;

let finalConfig;
if (false || userPrettier.overlay) {
    // overlay=true: 用户配置完全覆盖内置配置
    finalConfig = userPrettier.config || {};
} else {
    // overlay=false: 内置配置为基础，用户配置补充
    finalConfig = defu(userPrettier.config || {}, defaultPrettier);
}

export default finalConfig;
